name: shark-list
region: nyc
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: ajot/shark-list
    build_command: |
      npm install
      npm run build:css
    run_command: gunicorn --bind 0.0.0.0:8080 --workers 2 --threads 2 --timeout 120 wsgi:app
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        type: SECRET
      - key: API_KEY
        type: SECRET
      - key: API_SECRET
        type: SECRET
      - key: ACCESS_TOKEN
        type: SECRET
      - key: ACCESS_TOKEN_SECRET
        type: SECRET
      - key: LIST_ID
        type: SECRET
      - key: SYNC_COOLOFF_MINUTES
        value: "5"
